## Day-6 Agenda:
- intro about ML(Machine Learning)
    - For data analysis
      - Numpy
      - Pandas
      - matplotlib
     - seaborn
    - types of Machine Learning
     - Supervised Learning
      - Clasification
        - SVM(Suport Vector Machine)
        - Navie Bayes
        - K nearest Naighbor(KNN)
        - Random Forest
      - Regression
        - Linear Regression
        - Polynomial Regression
        - Logistic Regression
        - Decision Tree
     - Unsupervised Learning
      - Clustering
        - K Means
        - k median
        - Som
        - Historical
     - Reainforcement Learning
- FrameWork - Django
    - develop basic application 
    - project creation
     
- Heroku 
    - Deploying our project into sever
     - without DB
     - with DB(protgres sql)
     
     

### T-Shirt Size Prection


In [30]:
import pandas as pd
import numpy as np



In [31]:
# Get the data from source file
data=pd.read_csv('Tshirt.csv')
print(data)

    height  weight size
0      158    58.0    M
1      158    59.0    M
2      180   120.0  XXl
3      158    63.0    M
4      160    59.0    M
5      120    23.0    S
6      170    80.0   Xl
7      163    60.0    M
8      192   150.0  XXl
9      165    62.0    L
10     165    63.0    L
11     168     NaN    L
12     150    42.0    S
13     155    48.0    S
14     129    40.0    S
15     180    39.0    S
16     154   140.0  XXl
17     180    45.0    S
18     181    42.0    M


In [32]:
# data preprocessing
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   height  19 non-null     int64  
 1   weight  18 non-null     float64
 2   size    19 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 584.0+ bytes


In [33]:
data.isnull().sum()

height    0
weight    1
size      0
dtype: int64

In [34]:
data.fillna(0)

height  weight size
0      158    58.0    M
1      158    59.0    M
2      180   120.0  XXl
3      158    63.0    M
4      160    59.0    M
5      120    23.0    S
6      170    80.0   Xl
7      163    60.0    M
8      192   150.0  XXl
9      165    62.0    L
10     165    63.0    L
11     168     0.0    L
12     150    42.0    S
13     155    48.0    S
14     129    40.0    S
15     180    39.0    S
16     154   140.0  XXl
17     180    45.0    S
18     181    42.0    M

In [35]:
mean=data['weight'].mean()
print(mean)
#data.fillna(0)

66.27777777777777


In [36]:
# Huge no of null values
mean=data['weight'].mean()
print(mean)
data.fillna(mean)

66.27777777777777


height      weight size
0      158   58.000000    M
1      158   59.000000    M
2      180  120.000000  XXl
3      158   63.000000    M
4      160   59.000000    M
5      120   23.000000    S
6      170   80.000000   Xl
7      163   60.000000    M
8      192  150.000000  XXl
9      165   62.000000    L
10     165   63.000000    L
11     168   66.277778    L
12     150   42.000000    S
13     155   48.000000    S
14     129   40.000000    S
15     180   39.000000    S
16     154  140.000000  XXl
17     180   45.000000    S
18     181   42.000000    M

In [37]:
# Less Null Values in the database
data=data.dropna()
print(data)

    height  weight size
0      158    58.0    M
1      158    59.0    M
2      180   120.0  XXl
3      158    63.0    M
4      160    59.0    M
5      120    23.0    S
6      170    80.0   Xl
7      163    60.0    M
8      192   150.0  XXl
9      165    62.0    L
10     165    63.0    L
12     150    42.0    S
13     155    48.0    S
14     129    40.0    S
15     180    39.0    S
16     154   140.0  XXl
17     180    45.0    S
18     181    42.0    M


In [38]:
# x=Input values(Features),independent
# y=Output values(Target)/dependent
x=data[['weight','height']]
print(x)

    weight  height
0     58.0     158
1     59.0     158
2    120.0     180
3     63.0     158
4     59.0     160
5     23.0     120
6     80.0     170
7     60.0     163
8    150.0     192
9     62.0     165
10    63.0     165
12    42.0     150
13    48.0     155
14    40.0     129
15    39.0     180
16   140.0     154
17    45.0     180
18    42.0     181


In [39]:
# x=data[['weight','height']]
y=data['size']
print(y)

0       M
1       M
2     XXl
3       M
4       M
5       S
6      Xl
7       M
8     XXl
9       L
10      L
12      S
13      S
14      S
15      S
16    XXl
17      S
18      M
Name: size, dtype: object


In [40]:
x=data[['weight','height']]
y=data['size']
from sklearn.preprocessing import LabelEncoder
y_label=LabelEncoder()
Y=y_label.fit_transform(y)
print(Y)

[1 1 3 1 1 2 4 1 3 0 0 2 2 2 2 3 2 1]


In [41]:
x=data[['weight','height']]
y=data['size']
from sklearn.preprocessing import LabelEncoder
y_label=LabelEncoder()


In [42]:
# Modelling
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.3,random_state=3)
print(x_train)

    weight  height
6     80.0     170
7     60.0     163
13    48.0     155
9     62.0     165
18    42.0     181
17    45.0     180
5     23.0     120
0     58.0     158
16   140.0     154
8    150.0     192
3     63.0     158
10    63.0     165


In [43]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.3,random_state=3)
print(x_test)

    weight  height
12    42.0     150
2    120.0     180
1     59.0     158
15    39.0     180
4     59.0     160
14    40.0     129


In [44]:
# importing algorithm and apply to them
from sklearn.neighbors import KNeighborsClassifier 


In [45]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
print(knn.predict(x_test))


[1 0 1 1 1 1]


In [46]:
print(x_test)

    weight  height
12    42.0     150
2    120.0     180
1     59.0     158
15    39.0     180
4     59.0     160
14    40.0     129


In [47]:
knn.predict([[48,155]])

array([1])

In [48]:
knn.predict([[120,180]])

array([0])

In [49]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,knn.predict(x_test))*100)

33.33333333333333
