# Agenda

- pandas
    -> series
    ->data frames
    

In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.1.3'

In [3]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p16', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'comp

In [4]:
print(len(dir(pd)))

140


In [5]:
pd.

SyntaxError: invalid syntax (<ipython-input-5-bc888235687a>, line 1)

# pandas series

# hands on

In [7]:
import pandas as pd
import numpy as np

In [11]:
mydata=np.arange(30,100)
print(mydata)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77
 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [13]:
mydata=np.arange(30,100,10)
print(mydata)

[30 40 50 60 70 80 90]


In [14]:
mydata=np.arange(30,101,10)
print(mydata)

[ 30  40  50  60  70  80  90 100]


In [15]:
mypop_data=pd.Series(mydata)
print(mypop_data)

0     30
1     40
2     50
3     60
4     70
5     80
6     90
7    100
dtype: int32


In [16]:
mypop_data.name="population"

In [18]:
mypop_data.dtype

dtype('int32')

In [17]:
mypop_data.name

'population'

In [19]:
mypop_data[4]

70

In [20]:
mypop_data[1:4]

1    40
2    50
3    60
Name: population, dtype: int32

In [21]:
mypop_data[1:7:2]

1    40
3    60
5    80
Name: population, dtype: int32

In [22]:
mypop_data[::4]

0    30
4    70
Name: population, dtype: int32

In [23]:
# In million
g7_pop=pd.Series([23.234,34.211,43.342,54.346])

In [24]:
g7_pop.values

array([23.234, 34.211, 43.342, 54.346])

In [26]:
type(g7_pop.values)

numpy.ndarray

In [27]:
g7_pop.index

RangeIndex(start=0, stop=4, step=1)

In [28]:
mypop_data.index

RangeIndex(start=0, stop=8, step=1)

In [32]:
g7_pop.index=['a','b','c','d']
g7_pop


a    23.234
b    34.211
c    43.342
d    54.346
dtype: float64

In [33]:
mypop_data=pd.Series([23.234,34.211,43.342,54.346])

In [39]:
mypop_data.index=[
    'canada',
    'germany',
    'india',
    'italy'
]
mypop_data

canada     23.234
germany    34.211
india      43.342
italy      54.346
dtype: float64

In [40]:
r=pd.Series(np.array([1,2,3,4,5]))

In [41]:
r

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [42]:
r=pd.Series(np.array([1,2,3,4,5]),index=[1,2,3,4,5])

In [43]:
r

1    1
2    2
3    3
4    4
5    5
dtype: int32

In [44]:
r=pd.Series(np.array([1,2,3,4,5]),index=['a','b','c','d','e'])

In [45]:
r

a    1
b    2
c    3
d    4
e    5
dtype: int32

In [47]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [5]:
import pandas as pd
import numpy as np
r=pd.Series(np.array([1,2,3,4,5]),index=['a','b','c','d','e'],name='roll no',dtype=float)

In [6]:
r

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: roll no, dtype: float64

In [7]:
r=pd.Series(np.array([1,2,3,4,5]),index=['a','b','c','d','e'],name='roll no')

In [8]:
r

a    1
b    2
c    3
d    4
e    5
Name: roll no, dtype: int32

In [13]:
d={'a1':99,'a2':32,'a3':67,'a4':95,'a5':78}
d.items()

dict_items([('a1', 99), ('a2', 32), ('a3', 67), ('a4', 95), ('a5', 78)])

In [14]:
marks=pd.Series(d)
print(marks)

a1    99
a2    32
a3    67
a4    95
a5    78
dtype: int64


In [15]:
marks=pd.Series(d,name='S Marks')
print(marks)

a1    99
a2    32
a3    67
a4    95
a5    78
Name: S Marks, dtype: int64


In [16]:
marks=pd.Series(d,name='S Marks',dtype='str')
print(marks)

a1    99
a2    32
a3    67
a4    95
a5    78
Name: S Marks, dtype: object


In [17]:
marks['a1']

'99'

In [18]:
# how to get multiple values
marks['a1':'a4']

a1    99
a2    32
a3    67
a4    95
Name: S Marks, dtype: object