# Python Libraries


## numpy
#### it was created in 2005 by travis oliphant

In [1]:
import numpy as np
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [3]:
print(type(x))

<class 'numpy.ndarray'>


In [5]:
import numpy as np
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
import numpy as np 
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(z[2])

[ 9 10 11 12]


In [7]:
print(z[0,1])

2


In [8]:
print(z.ndim)

2


In [9]:
z.ndim

2

In [10]:
z.size

12

In [11]:
z.shape

(3, 4)

In [12]:
import numpy as np
s=np.array([1,2,3],ndmin=1)
print(s)

[1 2 3]


In [13]:
p=np.array([1,2,3],dtype=complex)
print(p)

[1.+0.j 2.+0.j 3.+0.j]


In [15]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
x[::2]

array([0, 2, 4, 6, 8])

In [17]:
x[0:9:3]

array([0, 3, 6])

In [20]:
n=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(n)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# reshapping of array

In [26]:
import numpy as np
n=np.arange(1,10).reshape((3,3))
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## concatenation of array

In [30]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.concatenate([x,y])
print(z)

[1 2 3 4 5 6]


In [32]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.concatenate([x,y])
z[2]+z[5]

9

## splitting of arrays

In [34]:
x=[1,2,3,9,9,3,2,1]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [9 9] [3 2 1]


In [37]:
a1=np.arange(100)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
a2=np.arange(100).reshape(10,10)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
a3=np.arange(15).reshape(3,5)
a3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
s1=np.ones((3,3))
print(s1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [45]:
s2=s1+3
print(s2)

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [47]:
s2=s1-1
print(s2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [48]:
s1=np.zeros((3,3))
print(s1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
print(np.sqrt(a1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563
 4.24264069 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152
 4.89897949 5.         5.09901951 5.19615242 5.29150262 5.38516481
 5.47722558 5.56776436 5.65685425 5.74456265 5.83095189 5.91607978
 6.         6.08276253 6.164414   6.244998   6.32455532 6.40312424
 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998 6.8556546
 6.92820323 7.         7.07106781 7.14142843 7.21110255 7.28010989
 7.34846923 7.41619849 7.48331477 7.54983444 7.61577311 7.68114575
 7.74596669 7.81024968 7.87400787 7.93725393 8.         8.06225775
 8.1240384  8.18535277 8.24621125 8.30662386 8.36660027 8.42614977
 8.48528137 8.54400375 8.60232527 8.66025404 8.71779789 8.77496439
 8.83176087 8.88819442 8.94427191 9.         9.05538514 9.11043358
 9.16515139 9.21954446 9.2736185  9.32737905 9.38083152 9.43398

In [50]:
print(np.sin(a1))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749
 -0.75098725  0.14987721  0.91294525  0.83665564 -0.00885131 -0.8462204
 -0.90557836 -0.13235175  0.76255845  0.95637593  0.27090579 -0.66363388
 -0.98803162 -0.40403765  0.55142668  0.99991186  0.52908269 -0.42818267
 -0.99177885 -0.64353813  0.29636858  0.96379539  0.74511316 -0.15862267
 -0.91652155 -0.83177474  0.01770193  0.85090352  0.90178835  0.12357312
 -0.76825466 -0.95375265 -0.26237485  0.67022918  0.98662759  0.39592515
 -0.55878905 -0.99975517 -0.521551    0.43616476  0.99287265  0.63673801
 -0.30481062 -0.96611777 -0.7391807   0.1673557   0.92002604  0.82682868
 -0.02655115 -0.85551998 -0.89792768 -0.11478481  0.77389068  0.95105465
  0.25382336 -0.67677196 -0.98514626 -0.38778164  0.56610764  0.99952016
  0.51397846 -0.44411267 -0.99388865 -0.62988799  0.

In [51]:
print(np.cos(a1))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462  0.40808206 -0.54772926 -0.99996083 -0.53283302
  0.42417901  0.99120281  0.64691932 -0.29213881 -0.96260587 -0.74805753
  0.15425145  0.91474236  0.83422336 -0.01327675 -0.84857027 -0.90369221
 -0.12796369  0.76541405  0.95507364  0.26664293 -0.66693806 -0.98733928
 -0.39998531  0.5551133   0.99984331  0.52532199 -0.43217794 -0.99233547
 -0.64014434  0.30059254  0.96496603  0.7421542  -0.16299078 -0.91828279
 -0.82930983  0.02212676  0.85322011  0.89986683  0.11918014 -0.77108022
 -0.95241298 -0.25810164  0.67350716  0.98589658  0.39185723 -0.56245385
 -0.99964746 -0.5177698   0.44014302  0.99339038  0.6333192  -0.30902273
 -0.96725059 -0.73619272  0.17171734  0.92175127  0.82433133 -0.03097503
 -0.85780309 -0.89597095 -0.11038724  0.77668598  0.

In [53]:
x=np.random.rand(2,5)
print(x)

[[0.87794139 0.7529622  0.51276344 0.91088659 0.26077495]
 [0.61754459 0.9718628  0.64332345 0.52021415 0.63875366]]


In [54]:
x1=np.random.randint(3,size=10)
print(x1)

[2 2 0 2 2 2 0 0 2 1]


In [55]:
x1=np.random.randint(4,size=10)
print(x1)

[1 3 3 2 2 2 1 3 2 3]


In [56]:
x1=np.random.randint(5,size=10)
print(x1)

[3 0 2 2 0 4 0 1 0 2]


In [57]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [58]:
print(len(dir(np)))

620


In [60]:
print(np.__version__)

1.19.2


## filtering arrays

In [64]:
import numpy as np
ary = np.array([11,12,13,14])
print(ary)
x=[True,False,True,False]
nary=ary[x]
print(nary)

[11 12 13 14]
[11 13]


In [65]:
import numpy as np
ary = np.array([11,12,13,14])
#print(ary)
x=[True,False,True,False]
nary=ary[x]
print(nary)

[11 13]


In [66]:
#create filter array for even number
ar=np.array([1,2,3,4,5])
filter_ar=ar%2==0
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[False  True False  True False]
[2 4]


In [69]:
# create filter array for odd number
ar=np.array([1,2,3,4,5,6,7])
filter_ar=ar%2!=0
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[ True False  True False  True False  True]
[1 3 5 7]


## statistical array
